# Generated by Django 4.0.1 on 2022-05-28 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by_obj', to=settings.AUTH_USER_MODEL)),
                ('following_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_to_obj', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
