# Generated by Django 4.0.1 on 2022-05-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='black-profile-picture.png', upload_to='profile_images'),
        ),
    ]
